#!/bin/sh
#
cd tidmod/ascii
./Tobinary
# binary versions of tidal models in tidmod
#
# now convert land-sea database
cd ../../lndsea
rm lndsea.[ib]??
gzcat lndsea.ascii.gz | ../bin/mapcon f
#
# now link files needed into the working area
#
cd ../working
ln -fs ../lndsea/lndsea.bit lndsea.bit
ln -fs ../lndsea/lndsea.ind lndsea.ind
ln -fs ../green/gr.gbaver.wef.p01.cm gr.gbaver.wef.p01.cm
ln -fs ../green/gr.gbcont.wef.p01.cm gr.gbcont.wef.p01.cm
ln -fs ../green/gr.gbocen.wef.p01.cm gr.gbocen.wef.p01.cm
ln -fs ../green/gr.gbaver.wef.p02.cm gr.gbaver.wef.p02.cm
ln -fs ../green/gr.gbcont.wef.p02.cm gr.gbcont.wef.p02.cm
ln -fs ../green/gr.gbocen.wef.p02.cm gr.gbocen.wef.p02.cm
ln -fs ../green/gr.gbaver.wef.p01.ce gr.gbaver.wef.p01.ce
ln -fs ../green/gr.gbcont.wef.p01.ce gr.gbcont.wef.p01.ce
ln -fs ../green/gr.gbocen.wef.p01.ce gr.gbocen.wef.p01.ce
ln -fs ../green/gr.gbaver.wef.p02.ce gr.gbaver.wef.p02.ce
ln -fs ../green/gr.gbcont.wef.p02.ce gr.gbcont.wef.p02.ce
ln -fs ../green/gr.gbocen.wef.p02.ce gr.gbocen.wef.p02.ce
ln -fs ../green/gr.gbcont.wef.p01.ce green.contap.std
ln -fs ../green/gr.gbaver.wef.p01.ce green.gbavap.std
ln -fs ../green/gr.gbocen.wef.p01.ce green.ocenap.std
ln -fs ../tidmod/k1.cortez.1976 k1.cortez.1976
ln -fs ../tidmod/k1.dtu10.tr.2010 k1.dtu10.tr.2010
ln -fs ../tidmod/k1.eot11a.2011 k1.eot11a.2011
ln -fs ../tidmod/k1.esr.aotim5.2004 k1.esr.aotim5.2004
ln -fs ../tidmod/k1.esr.cats.2008 k1.esr.cats.2008
ln -fs ../tidmod/k1.fes.2004 k1.fes.2004
ln -fs ../tidmod/k1.got4p7.2004 k1.got4p7.2004
ln -fs ../tidmod/k1.hamtide11a.2011 k1.hamtide11a.2011
ln -fs ../tidmod/k1.naoglobal.1999 k1.naoglobal.1999
ln -fs ../tidmod/k1.naoregional.1999 k1.naoregional.1999
ln -fs ../tidmod/k1.osu.amazon.2010 k1.osu.amazon.2010
ln -fs ../tidmod/k1.osu.bengal.2010 k1.osu.bengal.2010
ln -fs ../tidmod/k1.osu.bering.2010 k1.osu.bering.2010
ln -fs ../tidmod/k1.osu.chinasea.2010 k1.osu.chinasea.2010
ln -fs ../tidmod/k1.osu.europeshelf.2008 k1.osu.europeshelf.2008
ln -fs ../tidmod/k1.osu.gulfmex.2010 k1.osu.gulfmex.2010
ln -fs ../tidmod/k1.osu.hawaii.2010 k1.osu.hawaii.2010
ln -fs ../tidmod/k1.osu.hudson.2010 k1.osu.hudson.2010
ln -fs ../tidmod/k1.osu.mediterranean.2011 k1.osu.mediterranean.2011
ln -fs ../tidmod/k1.osu.namereast.2010 k1.osu.namereast.2010
ln -fs ../tidmod/k1.osu.northaustral.2009 k1.osu.northaustral.2009
ln -fs ../tidmod/k1.osu.okhotsk.2010 k1.osu.okhotsk.2010
ln -fs ../tidmod/k1.osu.patagonia.2010 k1.osu.patagonia.2010
ln -fs ../tidmod/k1.osu.persian.2010 k1.osu.persian.2010
ln -fs ../tidmod/k1.osu.redsea.2010 k1.osu.redsea.2010
ln -fs ../tidmod/k1.osu.tasmania.2010 k1.osu.tasmania.2010
ln -fs ../tidmod/k1.osu.tpxo72.2010 k1.osu.tpxo72.2010
ln -fs ../tidmod/k1.osu.tpxo72atlas.2011 k1.osu.tpxo72atlas.2011
ln -fs ../tidmod/k1.osu.usawest.2010 k1.osu.usawest.2010
ln -fs ../tidmod/k1.sfbay.1984 k1.sfbay.1984
ln -fs ../tidmod/k2.dtu10.tr.2010 k2.dtu10.tr.2010
ln -fs ../tidmod/k2.eot11a.2011 k2.eot11a.2011
ln -fs ../tidmod/k2.esr.aotim5.2004 k2.esr.aotim5.2004
ln -fs ../tidmod/k2.esr.cats.2008 k2.esr.cats.2008
ln -fs ../tidmod/k2.fes.2004 k2.fes.2004
ln -fs ../tidmod/k2.got4p7.2004 k2.got4p7.2004
ln -fs ../tidmod/k2.hamtide11a.2011 k2.hamtide11a.2011
ln -fs ../tidmod/k2.naoglobal.1999 k2.naoglobal.1999
ln -fs ../tidmod/k2.naoregional.1999 k2.naoregional.1999
ln -fs ../tidmod/k2.osu.amazon.2010 k2.osu.amazon.2010
ln -fs ../tidmod/k2.osu.bengal.2010 k2.osu.bengal.2010
ln -fs ../tidmod/k2.osu.bering.2010 k2.osu.bering.2010
ln -fs ../tidmod/k2.osu.chinasea.2010 k2.osu.chinasea.2010
ln -fs ../tidmod/k2.osu.europeshelf.2008 k2.osu.europeshelf.2008
ln -fs ../tidmod/k2.osu.gulfmex.2010 k2.osu.gulfmex.2010
ln -fs ../tidmod/k2.osu.hawaii.2010 k2.osu.hawaii.2010
ln -fs ../tidmod/k2.osu.hudson.2010 k2.osu.hudson.2010
ln -fs ../tidmod/k2.osu.mediterranean.2011 k2.osu.mediterranean.2011
ln -fs ../tidmod/k2.osu.namereast.2010 k2.osu.namereast.2010
ln -fs ../tidmod/k2.osu.okhotsk.2010 k2.osu.okhotsk.2010
ln -fs ../tidmod/k2.osu.patagonia.2010 k2.osu.patagonia.2010
ln -fs ../tidmod/k2.osu.persian.2010 k2.osu.persian.2010
ln -fs ../tidmod/k2.osu.redsea.2010 k2.osu.redsea.2010
ln -fs ../tidmod/k2.osu.tasmania.2010 k2.osu.tasmania.2010
ln -fs ../tidmod/k2.osu.tpxo72.2010 k2.osu.tpxo72.2010
ln -fs ../tidmod/k2.osu.tpxo72atlas.2011 k2.osu.tpxo72atlas.2011
ln -fs ../tidmod/k2.osu.usawest.2010 k2.osu.usawest.2010
ln -fs ../tidmod/m2.cortez.1976 m2.cortez.1976
ln -fs ../tidmod/m2.dtu10.tr.2010 m2.dtu10.tr.2010
ln -fs ../tidmod/m2.eot11a.2011 m2.eot11a.2011
ln -fs ../tidmod/m2.esr.aotim5.2004 m2.esr.aotim5.2004
ln -fs ../tidmod/m2.esr.cats.2008 m2.esr.cats.2008
ln -fs ../tidmod/m2.fes.2004 m2.fes.2004
ln -fs ../tidmod/m2.got4p7.2004 m2.got4p7.2004
ln -fs ../tidmod/m2.hamtide11a.2011 m2.hamtide11a.2011
ln -fs ../tidmod/m2.naoglobal.1999 m2.naoglobal.1999
ln -fs ../tidmod/m2.naoregional.1999 m2.naoregional.1999
ln -fs ../tidmod/m2.osu.amazon.2010 m2.osu.amazon.2010
ln -fs ../tidmod/m2.osu.bengal.2010 m2.osu.bengal.2010
ln -fs ../tidmod/m2.osu.bering.2010 m2.osu.bering.2010
ln -fs ../tidmod/m2.osu.chinasea.2010 m2.osu.chinasea.2010
ln -fs ../tidmod/m2.osu.europeshelf.2008 m2.osu.europeshelf.2008
ln -fs ../tidmod/m2.osu.gulfmex.2010 m2.osu.gulfmex.2010
ln -fs ../tidmod/m2.osu.hawaii.2010 m2.osu.hawaii.2010
ln -fs ../tidmod/m2.osu.hudson.2010 m2.osu.hudson.2010
ln -fs ../tidmod/m2.osu.mediterranean.2011 m2.osu.mediterranean.2011
ln -fs ../tidmod/m2.osu.namereast.2010 m2.osu.namereast.2010
ln -fs ../tidmod/m2.osu.northaustral.2009 m2.osu.northaustral.2009
ln -fs ../tidmod/m2.osu.okhotsk.2010 m2.osu.okhotsk.2010
ln -fs ../tidmod/m2.osu.patagonia.2010 m2.osu.patagonia.2010
ln -fs ../tidmod/m2.osu.persian.2010 m2.osu.persian.2010
ln -fs ../tidmod/m2.osu.redsea.2010 m2.osu.redsea.2010
ln -fs ../tidmod/m2.osu.tasmania.2010 m2.osu.tasmania.2010
ln -fs ../tidmod/m2.osu.tpxo72.2010 m2.osu.tpxo72.2010
ln -fs ../tidmod/m2.osu.tpxo72atlas.2011 m2.osu.tpxo72atlas.2011
ln -fs ../tidmod/m2.osu.usawest.2010 m2.osu.usawest.2010
ln -fs ../tidmod/m2.sfbay.1984 m2.sfbay.1984
ln -fs ../tidmod/m4.eot11a.2011 m4.eot11a.2011
ln -fs ../tidmod/m4.fes.2004 m4.fes.2004
ln -fs ../tidmod/m4.osu.amazon.2010 m4.osu.amazon.2010
ln -fs ../tidmod/m4.osu.chinasea.2010 m4.osu.chinasea.2010
ln -fs ../tidmod/m4.osu.europeshelf.2008 m4.osu.europeshelf.2008
ln -fs ../tidmod/m4.osu.northaustral.2009 m4.osu.northaustral.2009
ln -fs ../tidmod/m4.osu.okhotsk.2010 m4.osu.okhotsk.2010
ln -fs ../tidmod/m4.osu.patagonia.2010 m4.osu.patagonia.2010
ln -fs ../tidmod/m4.osu.tpxo72.2010 m4.osu.tpxo72.2010
ln -fs ../tidmod/m4.osu.tpxo72atlas.2011 m4.osu.tpxo72atlas.2011
ln -fs ../tidmod/mf.eot11a.2011 mf.eot11a.2011
ln -fs ../tidmod/mf.esr.cats.2008 mf.esr.cats.2008
ln -fs ../tidmod/mf.fes.2004 mf.fes.2004
ln -fs ../tidmod/mf.naoglobal.1999 mf.naoglobal.1999
ln -fs ../tidmod/mf.osu.hawaii.2010 mf.osu.hawaii.2010
ln -fs ../tidmod/mf.osu.tpxo72.2010 mf.osu.tpxo72.2010
ln -fs ../tidmod/mf.osu.tpxo72atlas.2011 mf.osu.tpxo72atlas.2011
ln -fs ../tidmod/mf.ray.equil.2004 mf.ray.equil.2004
ln -fs ../tidmod/mm.eot11a.2011 mm.eot11a.2011
ln -fs ../tidmod/mm.esr.cats.2008 mm.esr.cats.2008
ln -fs ../tidmod/mm.fes.2004 mm.fes.2004
ln -fs ../tidmod/mm.naoglobal.1999 mm.naoglobal.1999
ln -fs ../tidmod/mm.osu.hawaii.2010 mm.osu.hawaii.2010
ln -fs ../tidmod/mm.osu.tpxo72.2010 mm.osu.tpxo72.2010
ln -fs ../tidmod/mm.osu.tpxo72atlas.2011 mm.osu.tpxo72atlas.2011
ln -fs ../tidmod/mm.ray.equil.2004 mm.ray.equil.2004
ln -fs ../tidmod/n2.cortez.1976 n2.cortez.1976
ln -fs ../tidmod/n2.dtu10.tr.2010 n2.dtu10.tr.2010
ln -fs ../tidmod/n2.eot11a.2011 n2.eot11a.2011
ln -fs ../tidmod/n2.esr.aotim5.2004 n2.esr.aotim5.2004
ln -fs ../tidmod/n2.esr.cats.2008 n2.esr.cats.2008
ln -fs ../tidmod/n2.fes.2004 n2.fes.2004
ln -fs ../tidmod/n2.got4p7.2004 n2.got4p7.2004
ln -fs ../tidmod/n2.hamtide11a.2011 n2.hamtide11a.2011
ln -fs ../tidmod/n2.naoglobal.1999 n2.naoglobal.1999
ln -fs ../tidmod/n2.naoregional.1999 n2.naoregional.1999
ln -fs ../tidmod/n2.osu.amazon.2010 n2.osu.amazon.2010
ln -fs ../tidmod/n2.osu.bengal.2010 n2.osu.bengal.2010
ln -fs ../tidmod/n2.osu.bering.2010 n2.osu.bering.2010
ln -fs ../tidmod/n2.osu.chinasea.2010 n2.osu.chinasea.2010
ln -fs ../tidmod/n2.osu.europeshelf.2008 n2.osu.europeshelf.2008
ln -fs ../tidmod/n2.osu.gulfmex.2010 n2.osu.gulfmex.2010
ln -fs ../tidmod/n2.osu.hawaii.2010 n2.osu.hawaii.2010
ln -fs ../tidmod/n2.osu.hudson.2010 n2.osu.hudson.2010
ln -fs ../tidmod/n2.osu.mediterranean.2011 n2.osu.mediterranean.2011
ln -fs ../tidmod/n2.osu.namereast.2010 n2.osu.namereast.2010
ln -fs ../tidmod/n2.osu.okhotsk.2010 n2.osu.okhotsk.2010
ln -fs ../tidmod/n2.osu.patagonia.2010 n2.osu.patagonia.2010
ln -fs ../tidmod/n2.osu.persian.2010 n2.osu.persian.2010
ln -fs ../tidmod/n2.osu.redsea.2010 n2.osu.redsea.2010
ln -fs ../tidmod/n2.osu.tasmania.2010 n2.osu.tasmania.2010
ln -fs ../tidmod/n2.osu.tpxo72.2010 n2.osu.tpxo72.2010
ln -fs ../tidmod/n2.osu.tpxo72atlas.2011 n2.osu.tpxo72atlas.2011
ln -fs ../tidmod/n2.osu.usawest.2010 n2.osu.usawest.2010
ln -fs ../tidmod/o1.dtu10.tr.2010 o1.dtu10.tr.2010
ln -fs ../tidmod/o1.eot11a.2011 o1.eot11a.2011
ln -fs ../tidmod/o1.esr.aotim5.2004 o1.esr.aotim5.2004
ln -fs ../tidmod/o1.esr.cats.2008 o1.esr.cats.2008
ln -fs ../tidmod/o1.fes.2004 o1.fes.2004
ln -fs ../tidmod/o1.got4p7.2004 o1.got4p7.2004
ln -fs ../tidmod/o1.hamtide11a.2011 o1.hamtide11a.2011
ln -fs ../tidmod/o1.naoglobal.1999 o1.naoglobal.1999
ln -fs ../tidmod/o1.naoregional.1999 o1.naoregional.1999
ln -fs ../tidmod/o1.osu.amazon.2010 o1.osu.amazon.2010
ln -fs ../tidmod/o1.osu.bengal.2010 o1.osu.bengal.2010
ln -fs ../tidmod/o1.osu.bering.2010 o1.osu.bering.2010
ln -fs ../tidmod/o1.osu.chinasea.2010 o1.osu.chinasea.2010
ln -fs ../tidmod/o1.osu.europeshelf.2008 o1.osu.europeshelf.2008
ln -fs ../tidmod/o1.osu.gulfmex.2010 o1.osu.gulfmex.2010
ln -fs ../tidmod/o1.osu.hawaii.2010 o1.osu.hawaii.2010
ln -fs ../tidmod/o1.osu.hudson.2010 o1.osu.hudson.2010
ln -fs ../tidmod/o1.osu.mediterranean.2011 o1.osu.mediterranean.2011
ln -fs ../tidmod/o1.osu.namereast.2010 o1.osu.namereast.2010
ln -fs ../tidmod/o1.osu.northaustral.2009 o1.osu.northaustral.2009
ln -fs ../tidmod/o1.osu.okhotsk.2010 o1.osu.okhotsk.2010
ln -fs ../tidmod/o1.osu.patagonia.2010 o1.osu.patagonia.2010
ln -fs ../tidmod/o1.osu.persian.2010 o1.osu.persian.2010
ln -fs ../tidmod/o1.osu.redsea.2010 o1.osu.redsea.2010
ln -fs ../tidmod/o1.osu.tasmania.2010 o1.osu.tasmania.2010
ln -fs ../tidmod/o1.osu.tpxo72.2010 o1.osu.tpxo72.2010
ln -fs ../tidmod/o1.osu.tpxo72atlas.2011 o1.osu.tpxo72atlas.2011
ln -fs ../tidmod/o1.osu.usawest.2010 o1.osu.usawest.2010
ln -fs ../tidmod/o1.sfbay.1984 o1.sfbay.1984
ln -fs ../tidmod/p1.dtu10.tr.2010 p1.dtu10.tr.2010
ln -fs ../tidmod/p1.eot11a.2011 p1.eot11a.2011
ln -fs ../tidmod/p1.esr.aotim5.2004 p1.esr.aotim5.2004
ln -fs ../tidmod/p1.esr.cats.2008 p1.esr.cats.2008
ln -fs ../tidmod/p1.fes.2004 p1.fes.2004
ln -fs ../tidmod/p1.got4p7.2004 p1.got4p7.2004
ln -fs ../tidmod/p1.hamtide11a.2011 p1.hamtide11a.2011
ln -fs ../tidmod/p1.naoglobal.1999 p1.naoglobal.1999
ln -fs ../tidmod/p1.naoregional.1999 p1.naoregional.1999
ln -fs ../tidmod/p1.osu.amazon.2010 p1.osu.amazon.2010
ln -fs ../tidmod/p1.osu.bengal.2010 p1.osu.bengal.2010
ln -fs ../tidmod/p1.osu.bering.2010 p1.osu.bering.2010
ln -fs ../tidmod/p1.osu.chinasea.2010 p1.osu.chinasea.2010
ln -fs ../tidmod/p1.osu.europeshelf.2008 p1.osu.europeshelf.2008
ln -fs ../tidmod/p1.osu.gulfmex.2010 p1.osu.gulfmex.2010
ln -fs ../tidmod/p1.osu.hawaii.2010 p1.osu.hawaii.2010
ln -fs ../tidmod/p1.osu.hudson.2010 p1.osu.hudson.2010
ln -fs ../tidmod/p1.osu.mediterranean.2011 p1.osu.mediterranean.2011
ln -fs ../tidmod/p1.osu.namereast.2010 p1.osu.namereast.2010
ln -fs ../tidmod/p1.osu.okhotsk.2010 p1.osu.okhotsk.2010
ln -fs ../tidmod/p1.osu.patagonia.2010 p1.osu.patagonia.2010
ln -fs ../tidmod/p1.osu.persian.2010 p1.osu.persian.2010
ln -fs ../tidmod/p1.osu.redsea.2010 p1.osu.redsea.2010
ln -fs ../tidmod/p1.osu.tasmania.2010 p1.osu.tasmania.2010
ln -fs ../tidmod/p1.osu.tpxo72.2010 p1.osu.tpxo72.2010
ln -fs ../tidmod/p1.osu.tpxo72atlas.2011 p1.osu.tpxo72atlas.2011
ln -fs ../tidmod/p1.osu.usawest.2010 p1.osu.usawest.2010
ln -fs ../tidmod/q1.dtu10.tr.2010 q1.dtu10.tr.2010
ln -fs ../tidmod/q1.eot11a.2011 q1.eot11a.2011
ln -fs ../tidmod/q1.esr.aotim5.2004 q1.esr.aotim5.2004
ln -fs ../tidmod/q1.esr.cats.2008 q1.esr.cats.2008
ln -fs ../tidmod/q1.fes.2004 q1.fes.2004
ln -fs ../tidmod/q1.got4p7.2004 q1.got4p7.2004
ln -fs ../tidmod/q1.hamtide11a.2011 q1.hamtide11a.2011
ln -fs ../tidmod/q1.naoglobal.1999 q1.naoglobal.1999
ln -fs ../tidmod/q1.naoregional.1999 q1.naoregional.1999
ln -fs ../tidmod/q1.osu.amazon.2010 q1.osu.amazon.2010
ln -fs ../tidmod/q1.osu.bengal.2010 q1.osu.bengal.2010
ln -fs ../tidmod/q1.osu.bering.2010 q1.osu.bering.2010
ln -fs ../tidmod/q1.osu.chinasea.2010 q1.osu.chinasea.2010
ln -fs ../tidmod/q1.osu.europeshelf.2008 q1.osu.europeshelf.2008
ln -fs ../tidmod/q1.osu.gulfmex.2010 q1.osu.gulfmex.2010
ln -fs ../tidmod/q1.osu.hawaii.2010 q1.osu.hawaii.2010
ln -fs ../tidmod/q1.osu.hudson.2010 q1.osu.hudson.2010
ln -fs ../tidmod/q1.osu.mediterranean.2011 q1.osu.mediterranean.2011
ln -fs ../tidmod/q1.osu.namereast.2010 q1.osu.namereast.2010
ln -fs ../tidmod/q1.osu.okhotsk.2010 q1.osu.okhotsk.2010
ln -fs ../tidmod/q1.osu.patagonia.2010 q1.osu.patagonia.2010
ln -fs ../tidmod/q1.osu.persian.2010 q1.osu.persian.2010
ln -fs ../tidmod/q1.osu.redsea.2010 q1.osu.redsea.2010
ln -fs ../tidmod/q1.osu.tasmania.2010 q1.osu.tasmania.2010
ln -fs ../tidmod/q1.osu.tpxo72.2010 q1.osu.tpxo72.2010
ln -fs ../tidmod/q1.osu.tpxo72atlas.2011 q1.osu.tpxo72atlas.2011
ln -fs ../tidmod/q1.osu.usawest.2010 q1.osu.usawest.2010
ln -fs ../tidmod/s1.eot11a.2011 s1.eot11a.2011
ln -fs ../tidmod/s1.fes.2004 s1.fes.2004
ln -fs ../tidmod/s2.cortez.1976 s2.cortez.1976
ln -fs ../tidmod/s2.dtu10.tr.2010 s2.dtu10.tr.2010
ln -fs ../tidmod/s2.eot11a.2011 s2.eot11a.2011
ln -fs ../tidmod/s2.esr.aotim5.2004 s2.esr.aotim5.2004
ln -fs ../tidmod/s2.esr.cats.2008 s2.esr.cats.2008
ln -fs ../tidmod/s2.fes.2004 s2.fes.2004
ln -fs ../tidmod/s2.got4p7.2004 s2.got4p7.2004
ln -fs ../tidmod/s2.hamtide11a.2011 s2.hamtide11a.2011
ln -fs ../tidmod/s2.naoglobal.1999 s2.naoglobal.1999
ln -fs ../tidmod/s2.naoregional.1999 s2.naoregional.1999
ln -fs ../tidmod/s2.osu.amazon.2010 s2.osu.amazon.2010
ln -fs ../tidmod/s2.osu.bengal.2010 s2.osu.bengal.2010
ln -fs ../tidmod/s2.osu.bering.2010 s2.osu.bering.2010
ln -fs ../tidmod/s2.osu.chinasea.2010 s2.osu.chinasea.2010
ln -fs ../tidmod/s2.osu.europeshelf.2008 s2.osu.europeshelf.2008
ln -fs ../tidmod/s2.osu.gulfmex.2010 s2.osu.gulfmex.2010
ln -fs ../tidmod/s2.osu.hawaii.2010 s2.osu.hawaii.2010
ln -fs ../tidmod/s2.osu.hudson.2010 s2.osu.hudson.2010
ln -fs ../tidmod/s2.osu.mediterranean.2011 s2.osu.mediterranean.2011
ln -fs ../tidmod/s2.osu.namereast.2010 s2.osu.namereast.2010
ln -fs ../tidmod/s2.osu.northaustral.2009 s2.osu.northaustral.2009
ln -fs ../tidmod/s2.osu.okhotsk.2010 s2.osu.okhotsk.2010
ln -fs ../tidmod/s2.osu.patagonia.2010 s2.osu.patagonia.2010
ln -fs ../tidmod/s2.osu.persian.2010 s2.osu.persian.2010
ln -fs ../tidmod/s2.osu.redsea.2010 s2.osu.redsea.2010
ln -fs ../tidmod/s2.osu.tasmania.2010 s2.osu.tasmania.2010
ln -fs ../tidmod/s2.osu.tpxo72.2010 s2.osu.tpxo72.2010
ln -fs ../tidmod/s2.osu.tpxo72atlas.2011 s2.osu.tpxo72atlas.2011
ln -fs ../tidmod/s2.osu.usawest.2010 s2.osu.usawest.2010
ln -fs ../tidmod/s2.sfbay.1984 s2.sfbay.1984
ln -fs ../tidmod/ssa.ray.equil.2004 ssa.ray.equil.2004
ln -fs ../tidmod/z0.salton z0.salton
